if(NOT DEFINED PROBE OR NOT DEFINED SCHEMA OR NOT DEFINED OUTPUT_BASE)
  message(FATAL_ERROR "adapter test paths required")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef RUN_ID)
set(RUN_DIR "${OUTPUT_BASE}/${RUN_ID}")
execute_process(COMMAND "${PROBE}" "${SCHEMA}" "${RUN_DIR}" RESULT_VARIABLE RC)
if(NOT RC EQUAL 0)
  message(FATAL_ERROR "adapter native test failed: ${RC}")
endif()
